const portfolio = {
  filters: ["Featured", "React", "HTML", "Design", "Blogger", "All"],
  data: [
    {
      image: require("../assets/images/portfolio/coretecks.png"),
      title: "Coretecks.com",
      description: "Website developement uisng React",
      link: "https://coretecks.com/",
      tags: ["react"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/karim-sabry.png"),
      title: "Karim Sabry App",
      description: "Mobile App Design using AdobeXd",
      link:
        "https://xd.adobe.com/view/89033a08-6e06-44c8-55c2-fb3265b510f3-ff32",
      tags: ["design"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/bestdoc.png"),
      title: "Best1Doc",
      description: "Website Development using GatsbyJs",
      link: "https://best1doc.com/",
      tags: ["react", "gatsby"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/abdin.png"),
      title: "Abdin Pharamcies",
      description: "Abdin Group Website Design",
      link:
        "https://xd.adobe.com/view/0a08768e-bcce-49da-76fa-692f4e9b4772-7c39/",
      tags: ["design"],
      featured: true,
    },

    {
      image: require("../assets/images/portfolio/bassem.png"),
      title: "Bassem",
      description: "Pharamicies Mobile App Design",
      link:
        "https://xd.adobe.com/view/8c55f304-9229-48bf-7c00-47e2547d3a4b-fa64/",
      tags: ["design"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/julia.png"),
      title: "Julia",
      description: "Simple Resume / Portfolio Theme",
      link:
        "https://www.behance.net/gallery/89146929/Julia-Simple-Resume-Portfolio-Theme",
      tags: ["design"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/1.png"),
      title: "Classi",
      description: "Personal Blog XD-PSD Design",
      link: "https://www.behance.net/gallery/88599593/Classi-Blog-PSD-Template",
      tags: ["design"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/2.png"),
      title: "Pharmastan Store",
      description: "Store Website Design",
      link: "https://www.behance.net/gallery/88599837/PharmastanStore-Website",
      tags: ["design"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/4.png"),
      title: "Jskript",
      description: "Landing Page Design/Coding",
      link: "https://www.behance.net/gallery/82768347/JSKRIPT-LANDING-PAGE",
      tags: ["design", "html"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/5.png"),
      title: "BMAG Theme",
      description: "Magazine Responsive Blogger Template",
      link:
        "https://themeforest.net/item/bmag-magazine-responsive-blogger-template/8933899",
      tags: ["blogger"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/6.png"),
      title: "Fasel Theme",
      description: "News and magazine responsive blogger theme",
      link: "https://fasel-theme.blogspot.com/",
      tags: ["blogger"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/7.png"),
      title: "Baset Theme",
      description: "Creative Responsive Blogger Template",
      link: "http://baset-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/aflamy.png"),
      title: "Aflamy.online",
      description: "Website for online streaming Design/Coding",
      link: "http://aflamyonlinex.blogspot.com",
      tags: ["blogger"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/jblog.png"),
      title: "Jblog Theme",
      description: "Personal blog responsive blogger theme",
      link: "https://jblog-theme.blogspot.com/",
      tags: ["blogger"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/khafif.png"),
      title: "Khafeef Theme",
      description: "Personal blog responsive blogger theme",
      link: "https://khafeef-theme.blogspot.com/",
      tags: ["blogger"],
      featured: true,
    },
    {
      image: require("../assets/images/portfolio/cleansis.png"),
      title: "Cleansis Theme",
      description: "Clean grid responsive blogger template",
      link: "https://cleansis-template.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/videohat.png"),
      title: "Videohat Theme",
      description: "Blogger template for videos/youtube",
      link: "http://videohat-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/modounti.png"),
      title: "Modounti Theme",
      description: "Personal blogger template",
      link: "http://modounti-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/xmax.png"),
      title: "Xmax Theme",
      description: "Portfolio OnePage Blogger Template",
      link: "https://xmax-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/mosaor.png"),
      title: "Mosaor Theme",
      description: "Resposive blogger template",
      link: "http://mosaor.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/abda3.png"),
      title: "Abda' Theme",
      description: "Resposive Magazine blogger template",
      link: "http://abda3-mag.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/hdod.png"),
      title: "Hdod Theme",
      description: "Personal blogger template",
      link: "http://hdod-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/hroof.png"),
      title: "Hroof Theme",
      description: "News/Magazine blogger template",
      link: "http://hroof-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/arabi.png"),
      title: "ArabiFlat Theme",
      description: "Personal blogger template",
      link: "http://arabi-flat.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/badr.png"),
      title: "Badr Theme",
      description: "Clean blogger template",
      link: "https://badr-template.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
    {
      image: require("../assets/images/portfolio/enoml.png"),
      title: "Enoml Theme",
      description: "Personal blog template",
      link: "https://enoml-theme.blogspot.com/",
      tags: ["blogger"],
      featured: false,
    },
  ],
};

export default portfolio;
